name: Maven Build
run-name: ${{ github.actor }} | create package

on:
  workflow_dispatch:
  push:
    branches: main
    
jobs:
  DEV_BUILD:
    name: maven build
    runs-on: ubuntu-latest
    steps:
      - name: checkout codebase
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          cache: "maven"
      - name: verify java and mvn version
        run: |-
          echo "displaying java version"
          java -version
          
      - name: build package
        run: mvn clean install -DskipTests
      - name: upload artifact
        uses: actions/upload-artifacts@v3
        with:
          name: app.jar
          path: target/*.jar
      
      
  
