name: Maven Build
run-name: ${{ github.actor }} | create package

on:
  workflow_dispatch:
  push:
    branches: main
    
jobs:
  DEV_BUILD:
    name: maven build
    runs-on: ubuntu
    steps:
      - name: checkout codebase
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: "maven"
      - name: verify java and mvn version
        run: |-
          echo "displaying java version"
          java -version
          mvn -version
      - name: build package
        run: mvn clean install
      
      
  
